BASE_URL = "https://www.saucedemo.com/"
username_id = "username"
password_id = "password"
login_button_id = "login-button"
add_cart_buttons = "btn_inventory"
cart_button = "shopping_cart_link"
cart_items = "cart_item"
out_of_stock_button = "//div[@id='inventory_container']//div[@class='inventory_item'][1]//button"
errorMessage_xpath = "//*[@id='login_button_container']/div/form/div[3]/h3"
errorMessage_text = "Epic sadface: Username and password do not match any user in this service"
cart_button =  "cart_button_class"
add_to_cart_buttons = "add_cart_button_class"
out_of_stock_button  = "out_of_stock_button_xpath"

