# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from selenium import webdriver
from selenium.webdriver.common.by import By

class TestInvalidLogin:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
  
    def teardown_method(self, method):
        self.driver.quit()
  
    def test_invalid_login(self):
        self.driver.get("https://www.saucedemo.com/")
        self.driver.set_window_size(1536, 816)
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("username")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("password")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
        error_message = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"error\"]").text
        assert error_message == "Epic sadface: Username and password do not match any user in this service"


if __name__ == "__main__":
    test = TestInvalidLogin()
    test.setup_method(None)
    test.test_invalid_login()
    test.teardown_method(None)

  
